### PR TITLE
Add option to rotate through favorites

### PR DESCRIPTION
**Pull request by jashapiro**
Thank you for making this great Alfred workflow. 

I [posted earlier today](https://www.alfredforum.com/topic/21244-audio-switcher-swiftly-switch-audio-output-and-input-devices/#comment-111277) that it does almost exactly what I wanted, but that I wanted the option to rotate among my favorites with a single hotkey in addition to selecting particular devices.

So I decided to learn enough swift to be dangerous and implemented my own request here. The idea was just to extend the script so that it takes now one more command, `rotate_favorites` with the same `type` argument and then the favorites (newline separated). It then finds which of these is currently selected and choose the next in rotation. If none are selected, it chooses the first of the favorites.

I then wired up the Alfred workflow to allow this. I think in the process I removed the hotkeys you had set, because the default installation had removed them, and I was not so bold as to try to modify `info.plist` by hand.

I hope you find this a useful addition. Please let me know if there are any changes in code you would like me to make, or feel free to make any such changes on your own.

### CODE REVIEW

**Comment by TobiasMende** [comment]
Thank you for the PR @jashapiro. Great idea to add a rotation feature!

I imported it and gave it a try. It seems to work.

One thing that confuses me is the connection between the Remote buttons and the `rotate_favorites` node. Could you please explain what this is for? 

Maybe it would make sense to have two new remote buttons for rotation instead
Screenshot 2024-02-12 at 12 07 28

It could make sense to set the hotkeys as before (via Alfred) to keep the diff of the `info.plist` small. (Also unsure how updating the workflow behaves if this changes). For reference, the current hotkeys:

Screenshot 2024-02-12 at 12 08 20

**Comment by jashapiro** [comment]
Sorry about the remotes issue. My inexperience with Alfred workflows (and joy at my first foray into swift) had me confused about what the various inputs were. I have updated now with separate remote triggers, keeping your hotkeys, and hopefully a smaller diff.

**Comment by TobiasMende** [comment]
Thank you for the update! The connections look much better. I noticed one link missing from the "rotateInput" script to the "Post Notification" action.

I can now see the hotkey "F13" as the default – I actually do not have that on my keyboard (M1 MBP) – I am aware that every user can change it, but what do you think about setting a default that the internal MBP keyboard has?

What about CMD + F12 for output rotation and Option + F12 for input rotation? 

Regarding the Remote buttons, I think we can use the output icon for "rotate output" and the input icon for "rotate input" to make those more visually distinguishable on the remote.

I am happy to merge and adapt those things after, when bumping the version number. Please let me know what you think about this. 🙏😊

**Comment by jashapiro** [comment]
Thanks for the suggestions @TobiasMende! I have updated the default hotkeys and added the missing link. I also bumped the version number (which I realize you did not request; I misread your last sentence).

> Regarding the Remote buttons, I think we can use the output icon for "rotate output" and the input icon for "rotate input" to make those more visually distinguishable on the remote.

I made this update within the main `input.plist` file, but I do not have the remote app myself to check how the changes look there. As far as I can see it is set, though I used the blue icons for some distinction:
Screenshot 2024-02-21 at 8 51 20 AM

But rereading your last sentence, please do feel free to merge and adapt any remaining fixes as you prepare the next update!

**Comment by TobiasMende** [comment]
Thanks a lot for your contribution again. This looks great!

**Pull request merged**
